// Reference http://www.htmldog.com/references/css/properties/
export const visualFormatting = {
  width: 'width',
  height: 'height',
  minHeight: 'min-width',
  maxWidth: 'max-width',
  minHeight: 'min-height',
  maxHeight: 'max-height',
  position: 'position',
  top: 'top',
  right: 'right',
  bottom: 'bottom',
  left: 'left',
  clip: 'clip',
  overflow: 'overflow',
  zIndex: 'z-index',
  float: 'float',
  clear: 'clear',
  display: 'display',
  visibility: 'visibility',
}

export const boxModel = {
  margin: 'margin',
  marginTop: 'margin-top',
  marginRight: 'margin-right',
  marginBottom: 'margin-bottom',
  marginLeft: 'margin-left',
  padding: 'padding',
  paddingTop: 'padding-top',
  paddingRight: 'padding-right',
  paddingBottom: 'padding-bottom',
  paddingLeft: 'padding-left',
  border: 'border',
  borderTop: 'border-top',
  borderRight: 'border-right',
  borderBottom: 'border-bottom',
  borderLeft: 'border-left',
  borderWidth: 'border-width',
  borderTopWidth: 'border-top-width',
  borderRightWidth: 'border-right-width',
  borderBottomWidth: 'border-bottom-width',
  borderLeftWidth: 'border-left-width',
  borderStyle: 'border-style',
  borderTopStyle: 'border-top-style',
  borderRightStyle: 'border-right-style',
  borderBottomStyle: 'border-bottom-style',
  borderLeftStyle: 'border-left-style',
  borderColor: 'border-color',
  borderTopColor: 'border-top-color',
  borderRightColor: 'border-right-color',
  borderBottomColor: 'border-bottom-color',
  borderLeftColor: 'border-left-color',
}

export const colorsAndBackground = {
  color: 'color',
  opacity: 'opacity',
  backgroundColor: 'background-color',
  background: 'background-image',
  backgroundRepeat: 'background-repeat',
  backgroundPosition: 'background-position',
  backgroundAttachment: 'background-attachment',
  backgroundClip: 'background-clip',
  backgroundOrigin: 'background-origin',
  backgroundSize: 'background-size',
  borderRadius: 'border-radius',
  borderTopLeftRadius: 'border-top-left-radius',
  borderTopRightRadius: 'border-top-right-radius',
  borderBottomRightRadius: 'border-bottom-right-radius',
  borderBottomLeftRadius: 'border-bottom-left-radius',
  borderImage: 'border-image',
  borderImageSource: 'border-image-source',
  borderImageSlice: 'border-image-slice',
  borderImageWidth: 'border-image-width',
  borderImageOutset: 'border-image-outset',
  borderImageRepeat: 'border-image-repeat',
  boxShadow: 'box-shadow',
}

export const textAndFont = {
  font: 'font',
  fontFamily: 'font-family',
  fontSize: 'font-size',
  fontWeight: 'font-weight',
  fontStyle: 'font-style',
  fontVariant: 'font-variant',
  fontStretch: 'font-stretch',
  fontSizeAdjust: 'font-size-adjust',
  fontSynthesis: 'font-synthesis',
  lineHeight: 'line-height',
  letterSpacing: 'letter-spacing',
  wordSpacing: 'word-spacing',
  textAlign: 'text-align',
  textDecoration: 'text-decoration',
  textIndent: 'text-indent',
  textTransform: 'text-transform',
  verticalAlign: 'vertical-align',
  whiteSpace: 'white-space',
}
